# Generated by Django 3.2 on 2021-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=45)),
                ('phone_number', models.CharField(default='', max_length=45)),
                ('email', models.CharField(default='', max_length=45)),
                ('voicemail_number', models.CharField(default='', max_length=45)),
                ('company_id', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='assistant_config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='badges_config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='licenses_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='max_license',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_company',
            name='session_config',
            field=models.TextField(default=''),
        ),
    ]
