# Generated by Django 3.2.9 on 2021-11-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211125_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
